version: '3'
services:
  frontend:
    ports:
      - "${FRONTEND_PORT_HTTP}:80"
      - "${FRONTEND_PORT_HTTPS}:443"
  orborus:
    build: ./functions/onprem/orborus
    image: ghcr.io/frikky/shuffle-orborus:0.8.0
    container_name: shuffle-orborus
    hostname: shuffle-orborus
    networks:
      - shuffle
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - SHUFFLE_APP_SDK_VERSION=${SHUFFLE_APP_SDK_VERSION:-"0.8.0"}
      - SHUFFLE_WORKER_VERSION=${SHUFFLE_WORKER_VERSION:-"0.8.0"}
      - ORG_ID=${ORG_ID:-"Shuffle"}
      - ENVIRONMENT_NAME=${ENVIRONMENT_NAME:-"Shuffle"}
      - BASE_URL=http://${OUTER_HOSTNAME}:${BACKEND_PORT}
      - DOCKER_API_VERSION=${DOCKER_API_VERSION:-"1.40"}
      - SHUFFLE_PASS_WORKER_PROXY=${SHUFFLE_PASS_WORKER_PROXY}
      - SHUFFLE_ORBORUS_EXECUTION_TIMEOUT=600
      - SHUFFLE_BASE_IMAGE_NAME=${SHUFFLE_BASE_IMAGE_NAME}
      - SHUFFLE_BASE_IMAGE_REGISTRY=${SHUFFLE_BASE_IMAGE_REGISTRY}
      - SHUFFLE_BASE_IMAGE_TAG_SUFFIX=${SHUFFLE_BASE_IMAGE_TAG_SUFFIX}
      - HTTP_PROXY=${SHUFFLE_HTTP_PROXY}
      - HTTPS_PROXY=${SHUFFLE_HTTPS_PROXY}
    restart: unless-stopped
