name: "Close stale issues"
on:
  schedule:
  - cron: "30 1 * * *"

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/stale@v3
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        stale-issue-message: 'This issue has been automatically marked as stale because it has not had recent (30d) activity. Remove stale label or comment or this will be closed in 5 days. Thank you for your contributions.'
        stale-pr-message: 'This pull request has been automatically marked as stale because it has not had recent (30d) activity. Remove stale label or comment or this will be closed in 5 days. Thank you for your contributions.'
        days-before-stale: 30
        days-before-close: 5
